# Generated by Django 2.1.5 on 2019-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20190308_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehistory',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feehistory',
            name='paiddate',
            field=models.DateTimeField(null=True),
        ),
    ]
