# Generated by Django 2.1.5 on 2019-03-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_feehistory_paiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_paid',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_due_date',
            field=models.DateField(null=True),
        ),
    ]
