# Generated by Django 2.1.5 on 2019-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_auto_20190315_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_paid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
